### PR TITLE
Update bot.hi.yml

### PR DESCRIPTION
**Pull request by Architrixs**
translated slowmodesec to hindi

### CODE REVIEW

**Comment by Architrixs** [comment]
For issue https://github.com/GabrielRF/Send2KindleBot/issues/86 Please Link the issue from your side.

**Review by GabrielRF — APPROVED** [review]

**Comment by GabrielRF** [comment]
@Architrixs Thank you very much!

**Comment by Architrixs** [comment]
Hey, Thanks... can you Please add label:hacktoberfest-accepted.

**Comment by GabrielRF** [comment]
@Architrixs Like this?

**Pull request merged**
