### PR TITLE
Translate bot into Swedish

### PR DESCRIPTION
**Pull request by nulf**
Created a new translations file and translated all the strings to Swedish

### CODE REVIEW

**Comment by GabrielRF** [comment]
@nulf Wow! 
Thank you very much! 
I'm accepting it. Could you please send `/start` to the bot and check if it worked?

**Comment by nulf** [comment]
Can't find kindle.conf_sample? I might be blind. Haven't actually used the app, doing some hacktoberfest contributions.

**Comment by GabrielRF** [comment]
@nulf You are correct. The example is missing. I'll fix it asap.
If you don't have Telegram, don't worry. I'll try to test it myself. 
Thank you, one more time!

**Comment by nulf** [comment]
No problem, thanks for accepting the merge request! :)

**Pull request merged**
